./mmDisasm.py baserom_mm_ntsc_usa/ovl_title
./mmDisasm.py baserom_mm_ntsc_usa/ovl_select
./mmDisasm.py baserom_mm_ntsc_usa/ovl_opening
./mmDisasm.py baserom_mm_ntsc_usa/ovl_file_choose
./mmDisasm.py baserom_mm_ntsc_usa/ovl_daytelop
./mmDisasm.py baserom_mm_ntsc_usa/ovl_kaleido_scope
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Player_Actor
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_GirlA
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Part
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Light
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Door
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Box
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pametfrog
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Okuta
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bom
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wallmas
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dodongo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Firefly
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Horse
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Arrow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Elf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Niw
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tite
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Peehat
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Holl
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dinofos
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hata
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zl1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Viewer
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bubble
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Door_Shutter
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boom
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Torch2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Minifrog
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_St
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Wturn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_River_Sound
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ossan
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Famos
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bombf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Am
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dekubaba
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_M_Fire1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_M_Thunder
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Breakwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Door_Warp1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Syokudai
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Item_B_Heart
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dekunuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bbfall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Arms_Hook
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Keikoku_Spr
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wood02
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Death
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Minideath
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Vm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Effect
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Kankyo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Floormas
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rd
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_F40_Flift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Mure
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sw
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Object_Kankyo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Horse_Link_Child
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Door_Ana
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Encount1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Tre_Lgt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Encount2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fire_Rock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ctower_Rot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Mir_Ray
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bigslime
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Karebaba
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_In
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bom_Chu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Horse_Game_Check
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rr
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fr
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fishing
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Oshihiki
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Dust
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Umajump
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Insect
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Butte
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fish
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Item_Etcetera
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Arrow_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Arrow_Ice
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Arrow_Light
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kibako
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tsubo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ik
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Shd
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dns
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Honotrap
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tubo_Trap
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Ice_Poly
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fz
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kusa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Bean
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Bombiwa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Switch
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Lift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hsblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Okarina_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Goroiwa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Daiku
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Nwc
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Item_Inbox
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ge1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Blockstop
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sda
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Clear_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ms
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hs
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ingate
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kanban
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Attack_Niw
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Owl
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hana
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Lightswitch
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Mure2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Stream
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Weather_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ani
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Js
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Okarina_Effect
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_F40_Swlift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kakasi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Makeoshihiki
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Spot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Torch
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Shot_Sun
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Roomtimer
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ssh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Dust
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Kirakira
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Bomb2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Blast
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_G_Spk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_D_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Bubble
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_G_Ripple
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_G_Splash
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_G_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Lightning
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Dt_Bubble
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Hahen
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Stick
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Sibuki
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Stone1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Hitmark
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Fhg_Flash
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_K_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Solder_Srch_Ball
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Kakera
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Ice_Piece
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_En_Ice
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Fire_Tail
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_En_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Extra
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Dead_Db
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Dead_Dd
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Dead_Ds
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Storm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Demo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Minislime
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Nutsball
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Si
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Comb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kibako2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hs2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Mure3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Skb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gs
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Sound
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Crow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Cow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Ice_Smoke
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Makekinsuta
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ge3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hamishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zl4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mm2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Door_Spiral
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Pzlblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Toge
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Armos
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Boyo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Grasshopper
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Grass
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Grass_Carry
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Grass_Unit
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Fire_Wall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Encount3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Jso
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Chikuwa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Knight
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Warp_tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Aob_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boj_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boj_02
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boj_03
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Encount4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bom_Bowl_Man
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Syateki_Man
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Icicle
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Syateki_Crow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boj_04
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Cne_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bba_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bji_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Spdweb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mt_tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_02
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_03
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_04
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_05
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_06
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_07
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dy_Yoseizo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Boj_05
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sob1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Go
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Raf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Funen
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Raillift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Numa_Hana
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Flowerpot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Spinyroll
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Hina
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Syateki_Wf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Skateblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_En_Ice_Block
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Iceblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bigpamet
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dblue_Movebg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Syateki_Dekunuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Ravine
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Sa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Slime
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pr
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Toudai
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Entotu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Bell
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Syateki_Okuta
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Shutter
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Zl
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ru
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Elfgrp
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Tsg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Baguo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Vspinyroll
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Smork
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bat
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sekihi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wiz
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wiz_Brock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wiz_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Change
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Statue
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Fireshield
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ladder
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mkk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Getitem
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dnb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dnh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dnk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dnq
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Keikoku_Saku
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hugebombiwa
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Firefly2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rat
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Water_Effect
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kusa2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Spout_Fire
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dy_Extra
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bal
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ginko_Man
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Warp_Uzu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Driftice
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Look_Nuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mushi2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mm3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Crace_Movebg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dno
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pr2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Prz
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Jso2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Etcetera
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Egol
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Mine
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Purify
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tru
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Trt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test6
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Az
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Estone
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Hakugin_Post
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Opstage
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Stk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char00
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char02
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char03
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char04
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char05
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char06
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char07
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char08
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Char09
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tokeidai
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Mnk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Egblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Guard_Nuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Hakugin_Bombwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tokei_Tobira
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Hakugin_Elvpole
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ma4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Twig
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Po_Fusen
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Door_Etc
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bigokuta
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Icefloe
./mmDisasm.py baserom_mm_ntsc_usa/ovl_fbdemo_triforce
./mmDisasm.py baserom_mm_ntsc_usa/ovl_fbdemo_wipe1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_fbdemo_wipe3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_fbdemo_wipe4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_fbdemo_wipe5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Effect_Ss_Sbn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Ocarinalift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Time_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Open_Shutter
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Open_Spot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Fu_Kaiten
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Aqua
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Elforg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Elfbub
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fu_Mato
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fu_Kago
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Osn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ctower_Gear
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Trt2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tokei_Step
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Lotus
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kame
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Takaraya_Wall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Fu_Mizu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sellnuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dkjail_Ivy
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Visiblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Takaraya
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tsn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ds2n
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fsn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Shn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Stop_heishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Bigicicle
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Lift_Nuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Market_Step
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Lupygamelift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Test7
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Lightblock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Mir_Ray2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Wdhand
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gamelupy
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Danpei_Movebg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Snowwd
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gakufu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Col_Man
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Talk_Gibud
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Giant
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Snowball
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Boss_Hakugin
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gb2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Onpuman
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Tobira01
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tag_Obj
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Dhouse
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hakaisi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Hakugin_Switch
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Snowman
./mmDisasm.py baserom_mm_ntsc_usa/ovl_TG_Sw
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Po_Sisters
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pp
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hakurock
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hanabi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Dowsing
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Wind
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Racedog
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kendo_Js
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Botihasira
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fish2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pst
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Poh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Spidertent
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zoraegg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kbt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Maruta
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Snowball2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gg2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Ghaka
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dnp
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dai
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Goron_Oyu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kgy
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Invadepoh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Gk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_An
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bee
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dragon
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Dora
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bigpo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kendo_Kanban
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hariko
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sth
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Sinkai_Kabe
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Haka_Curtain
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Kin2_Bombwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Kin2_Fence
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Kin2_Picture
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Kin2_Shelf
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rail_Skb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Jg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tru_Mt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Um
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Neo_Reeba
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Mbar_Chair
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Block
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Mirror
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Rotaryroom
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dblue_Balance
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dblue_Waterfall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kaizoku
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ge2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ma_Yts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ma_Yto
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tokei_Turret
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Dblue_Elevator
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Warpstone
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zog
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Rotlift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Jg_Gakki
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Inibs_Movebg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Tree
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Y2lift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Y2shutter
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Boat
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Taru
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hunsui
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Jc_Mato
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Mir_Ray3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zob
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Elf_Msg6
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Nozoki
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Toto
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Railgibud
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Baba
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Suttari
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zod
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kujiya
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Geg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kinoko
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Yasi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron1
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Chan
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zos
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_S_Goro
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Nb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ja
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_F40_Block
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_F40_Switch
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Po_Composer
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Guruguru
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Stone_heishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe6
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Scopenuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Scopecrow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Oceff_Wipe7
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Kamejima_Wave
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hgo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zov
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ah
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Hgdoor
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Bombwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Ray
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Shutter
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Haka_Bombwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Haka_Tomb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sc_Ruppe
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Iknv_Doukutu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Iknv_Obj
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Pamera
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_HsStump
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hidden_Nuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Zow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Talk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Al
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tab
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Nimotsu
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hit_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ruppecrow
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Tanron6
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Daiku2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Muto
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Baisen
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Heishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Demo_heishi
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Dt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Cha
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Dinner
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Lastday
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikana_Dharma
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Akindonuts
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Stk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ig
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rg
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Osk
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Sth2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Yb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rz
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Scopecoin
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bjt
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bomjima
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bomjimb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bombers
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bombers2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bombal
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Moon_Stone
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Mu_Pict
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Ikninside
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Eff_Zoraband
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kepn_Koya
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Usiyane
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Nnh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Kzsaku
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Milk_Bin
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Kitan
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Astr_Bombwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Iknin_Susceil
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bsb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Recepgirl
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Thiefbird
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Jgame_Tsn
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Jgame_Light
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Yado
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Syoten
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Demo_Moonend
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Lbfshot
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Bg_Last_Bwall
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_And
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Invadepoh_Demo
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Danpeilift
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Fall2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Al
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_An
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Ah
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Nb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Drs
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Bal
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Paper
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Hint_Skb
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Tag
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Bh
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero2
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero3
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero4
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero5
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Ending_Hero6
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Dm_Gm
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Swprize
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Invisible_Ruppe
./mmDisasm.py baserom_mm_ntsc_usa/ovl_Obj_Ending
./mmDisasm.py baserom_mm_ntsc_usa/ovl_En_Rsn