/* SPDX-FileCopyrightText: © 2024 Decompollaborate */
/* SPDX-License-Identifier: MIT */

use alloc::collections::BTreeSet;

use alloc::string::String;

use rabbitizer::vram::VramOffset;
use rabbitizer::Vram;

use crate::context::Context;
use crate::metadata::SymbolMetadata;
use crate::rom_address::RomAddress;
use crate::symbols::Symbol;

pub struct SectionBase {
    name: String,

    rom: Option<RomAddress>,
    vram: Vram,

    // in_section_offset: u32,
    // section_type: SectionType,
}

impl SectionBase {
    pub fn new(name: String, rom: Option<RomAddress>, vram: Vram, ) -> Self {
        Self {
            name,
            rom,
            vram,
        }
    }
}

impl SectionBase {
    pub fn vram_offset(&self, local_offset: usize) -> Vram {
        self.vram.add_offset(&VramOffset::new(local_offset as i32))
    }
    pub fn rom_offset(&self, local_offset: usize) -> Option<RomAddress> {
        if let Some(rom) = self.rom {
            // TODO
            Some(RomAddress::new(rom.inner() + local_offset as u32))
        } else {
            None
        }
    }
}

impl<'context> SectionBase {
    pub fn find_symbol(&self, context: &'context Context, vram: Vram, rom: Option<RomAddress>, check_addend: bool, check_upper_limit: bool, check_global_segment: bool) -> Option<&'context SymbolMetadata> {
        // TODO
        None
    }

    pub fn add_function(&mut self, context: &'context mut Context, vram: Vram, rom: Option<RomAddress>, is_autogenerated: bool) -> &'context mut SymbolMetadata {
        todo!()
    }
}

pub trait Section {
    fn section_base(&self) -> &SectionBase;
    fn symbol_list(&self) -> &[impl Symbol];
    fn symbols_vrams(&self) -> &BTreeSet<Vram>;
}
